In [1]:
!pip install numpy


In [3]:
import numpy as np

## Numpy :

- It is a Python library that provides a multidimensional array.
- NumPy is an open source mathematical and scientific computing library for Python programming tasks.

In [8]:
## To access the numpy libraries we should install it.

!pip install numpy

In [10]:
## to acess numpy import it

import numpy as np

In [12]:
A = np.array([1,2,3])

In [14]:
print(A)

[1 2 3]


- Numpy is Classfied into 3 types :

 
    1) One Dimensional Array.
    2) Two Dimenssional Array.
    3) Three Dimenssional Array.

## One Dimenssional Array :

- The One-dimensional array contains elements only in one dimension.
- One Dimenssional Array deals with only rows.
- A One dimensional array, also known as a 1D array,

In [27]:
A = np.array([7,11])

In [29]:
print(A)

[ 7 11]


In [33]:
h = np.array([100,108])

In [35]:
print(h)

[100 108]


## Two Dimenssional Array :

- A two-dimensional array, also known as a 2D array.
- Two Dimenssional Array deals with  rows and Columns.

In [42]:
a = np.array([[1,2,3],[4,5,6]])

In [44]:
print(a)

[[1 2 3]
 [4 5 6]]


In [64]:
b = np.array([[3,2,1],[6,5,4]])

In [66]:
print(b)

[[3 2 1]
 [6 5 4]]


## Three Dimenssional Array :

- A three-dimensional array, also known as a 3D array.
- And consists of 3d rows,columns and shapes.

In [68]:
d = np.array([[[1,1,1],[2,2,2],[3,3,3]]]) 

In [70]:
print(d)

[[[1 1 1]
  [2 2 2]
  [3 3 3]]]


## Placeholder :

- Placeholder.
   1) Zeros
   2) Ones 

## * Zeros :

- This function is used to replace the matrix values to zeros because it is called as "Zeros".

In [97]:
A = np.zeros([5,2,3])

In [99]:
print(A)

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [113]:
b= np.zeros([2,5,9])

In [117]:
print(b)

[[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]]]


## * Ones :

In [103]:
A= np.ones([5,2,3])

In [105]:
print(A)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [127]:
s = np.ones([2,5,5])

In [129]:
print(s)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


##  Create Evenly Spaced Values :

In [155]:
q= np.arange(11,50,4)

In [157]:
print(q)

[11 15 19 23 27 31 35 39 43 47]


In [159]:
d = np.arange(100,1000,20)

In [161]:
print(d)

[100 120 140 160 180 200 220 240 260 280 300 320 340 360 380 400 420 440
 460 480 500 520 540 560 580 600 620 640 660 680 700 720 740 760 780 800
 820 840 860 880 900 920 940 960 980]


In [237]:
y = np.arange(1,1000,142)

In [239]:
print(y)

[  1 143 285 427 569 711 853 995]


In [214]:
r = np.arange(10,100,5)

In [216]:
print(r)

[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


## evenly spaced samples:

In [254]:
k = np.linspace(1,20,40)   #(starting point ,Ending point,how many times it should divide)

In [256]:
print(k)

[ 1.          1.48717949  1.97435897  2.46153846  2.94871795  3.43589744
  3.92307692  4.41025641  4.8974359   5.38461538  5.87179487  6.35897436
  6.84615385  7.33333333  7.82051282  8.30769231  8.79487179  9.28205128
  9.76923077 10.25641026 10.74358974 11.23076923 11.71794872 12.20512821
 12.69230769 13.17948718 13.66666667 14.15384615 14.64102564 15.12820513
 15.61538462 16.1025641  16.58974359 17.07692308 17.56410256 18.05128205
 18.53846154 19.02564103 19.51282051 20.        ]


In [258]:
A = np.linspace(100,1000,10)

In [260]:
print(A)

[ 100.  200.  300.  400.  500.  600.  700.  800.  900. 1000.]
